apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app-1
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: test-app1-ns
    repoURL: https://github.com/ginilekshmi/app-of-apps-child
    targetRevision: HEADD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
