apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
spec:
  destination:
    name: parent
    namespace: test-apps
    server: https://kubernetes.default.svc
  source:
    path: ./
    repoURL: https://github.com/diksha1999/app-of-apps-child
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true