apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vend-child
  namespace: test-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: vend-child
    namespace: test-apps
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: "charts/vend-helm"
    repoURL: "https://github.com/thomassuedbroecker/vend-helm"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
