apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app-1
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: apps/namespaces
    repoURL: https://github.com/diksha1999/app-of-apps-by-diksha
    targetRevision: HEAD
  sources: []
  project: parent
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
