---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
  labels:
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: test3
  labels:
    environment: production
